recipes-dom0/dom0-image-weston/dom0-image-weston.bbappend
recipes-domu/domu-image-weston/domu-image-weston.bbappend

No need to do extra work with immediate variable expansion
as it is already handled by bitbake itself.

Simplify XT_QUIRK_UNPACK_SRC_URI usage

---

recipes-domu/domu-image-weston/domu-image-weston.bbappend
recipes-domu/domu-image-weston/files/meta-xt-prod-extra/recipes-core/images/core-image-minimal-initramfs.bbappend

Build initramfs for DomU

---

recipes-dom0/dom0-image-weston/files/meta-xt-prod-extra/recipes-extended/guest-addons/files/domu-nfs-coproc.cfg
recipes-dom0/dom0-image-weston/files/meta-xt-prod-extra/recipes-kernel/linux/linux-renesas/r8a7795-salvator-x-dom0.dts
recipes-dom0/dom0-image-weston/files/meta-xt-prod-extra/recipes-kernel/linux/linux-renesas/r8a7795-salvator-x-domu.dts

Add changes required to run with IPMMU and SCF.

Add changes from otyshchenko1/rcar-3.5.3-iommu-coproc

---

recipes-dom0/dom0-image-weston/files/meta-xt-prod-extra/recipes-extended/xen/xen_git.bbappend

Signed-off-by: Iurii Artemenko <Iurii_Artemenko@epam.com>

Fix issue #12: Align Xen installation between Yocto and native

---

recipes-dom0/dom0-image-weston/files/meta-xt-prod-extra/recipes-kernel/linux/linux-renesas_%.bbappend

Fix issue #15: kernel: make generic symlink to dtb(s)

---

recipes-dom0/dom0-image-weston/files/meta-xt-prod-extra/recipes-extended/guest-addons/files/snd_be.cfg
recipes-dom0/dom0-image-weston/files/meta-xt-prod-extra/recipes-extended/guest-addons/guest-addons.bb
recipes-dom0/dom0-image-weston/files/meta-xt-prod-extra/recipes-extended/sndbe/sndbe_git.bbappend
recipes-dom0/dom0-image-weston/files/meta-xt-prod-extra/recipes-graphics/images/core-image-weston.bbappend

Add configuration file and configure "sndbe".

Add "sndbe" into the final image

---

recipes-dom0/dom0-image-weston/dom0-image-weston.bbappend
recipes-dom0/dom0-image-weston/files/meta-xt-prod-extra/recipes-graphics/gles-module/gles-user-module.bbappend
recipes-dom0/dom0-image-weston/files/meta-xt-prod-extra/recipes-kernel/kernel-module-gles/kernel-module-gles.bbappend
recipes-domu/domu-image-weston/domu-image-weston.bbappend
recipes-domu/domu-image-weston/files/meta-xt-prod-extra/recipes-graphics/gles-module/files/72-pvr-seat.rules.patch
recipes-domu/domu-image-weston/files/meta-xt-prod-extra/recipes-kernel/kernel-module-gles/kernel-module-gles.bbappend

Add support for vgpu-img development product

---

recipes-domu/domu-image-weston/domu-image-weston.bbappend
recipes-domu/domu-image-weston/files/meta-xt-prod-extra/recipes-core/images/core-image-minimal-initramfs.bbappend

Remove unused initramfs image

---

recipes-dom0/dom0-image-weston/files/meta-xt-prod-extra/recipes-core/base-files/base-files_%.bbappend
recipes-domu/domu-image-weston/files/meta-xt-prod-extra/recipes-core/base-files/base-files_%.bbappend

Add domain name to hostname prompt

---

recipes-dom0/dom0-image-weston/dom0-image-weston.bbappend
recipes-domu/domu-image-weston/domu-image-weston.bbappend

Rename meta-layer to make it clear between meta-renesas and meta-tx

---

recipes-dom0/dom0-image-weston/files/meta-xt-prod-extra/recipes-graphics/wayland/weston_1.11.0.bbappend
recipes-domu/domu-image-weston/files/meta-xt-prod-extra/recipes-graphics/wayland/weston_1.11.0.bbappend

Move Weston recipe to product specific

---

recipes-dom0/dom0-image-weston/files/meta-xt-prod-extra/recipes-bsp/arm-trusted-firmware/arm-trusted-firmware_git.bbappend

Switch arm-trusted-firmware to xen-troops repository

---

recipes-dom0/dom0-image-rescue-initramfs/dom0-image-rescue-initramfs.bbappend
recipes-dom0/dom0-image-rescue-initramfs/files/meta-xt-prod-extra/recipes-kernel/linux/linux-generic-armv8.bbappend
recipes-dom0/dom0-image-thin-initramfs/dom0-image-thin-initramfs.bbappend
recipes-dom0/dom0-image-thin-initramfs/files/meta-xt-prod-extra/recipes-extended/xen/xen_git.bbappend
recipes-dom0/dom0-image-thin-initramfs/files/meta-xt-prod-extra/recipes-kernel/linux/linux-generic-armv8.bbappend
recipes-domd/agl/files/meta-xt-prod-extra/recipes-extended/xen/xen_git.bbappend
recipes-domd/agl/files/meta-xt-prod-extra/recipes-kernel/linux/linux-renesas_%.bbappend
recipes-domu/domu-image-android/files/meta-xt-prod-extra/recipes-extended/android/android.bbappend
recipes-domu/domu-image-fusion/files/meta-xt-prod-extra/recipes-kernel/linux/linux-generic-armv8.bbappend

Set current development revisions to meta-layers and components

---

recipes-dom0/dom0-image-thin-initramfs/dom0-image-thin-initramfs.bbappend
recipes-dom0/dom0-image-thin-initramfs/files/meta-xt-prod-extra/recipes-extended/xen/xen_git.bbappend
recipes-domd/agl/files/meta-xt-prod-extra/recipes-extended/xen/xen_git.bbappend
recipes-domd/agl/inc/domd-agl-image.inc

Promote used XEN version to 4.10.0.

prod-devel: upgrade XEN

---

recipes-dom0/dom0-image-thin-initramfs/files/meta-xt-prod-extra/recipes-extended/xen/xen_git.bbappend

Fix typo in XEN_REL

---

doc/mk_sdcard_image.sh

Add SD card image builder script

---

recipes-domu/domu-image-fusion/files/meta-xt-prod-extra/doc/local.conf.domf-image-minimal

Use init system with systemd over SysV init

---

doc/mk_sdcard_image_domu.sh
recipes-domd/domd-image-weston/domd-image-weston.bbappend

Depending on which guest domains are built we need to install
different mk_sdcard_image scripts, e.g. if DomU flavor is built,
then the script will create an SD card with Dom0/D/U.

Install mk_sdcard_image script depending on flavor

---

recipes-domu/domu-image-weston/files/meta-xt-prod-extra/recipes-graphics/gles-module/gles-user-module_1.9.bbappend

Fix path for PowerVR device nodes.

Tune udev rules for DomU

---

recipes-domd/domd-image-weston/files/meta-xt-prod-extra/recipes-bsp/u-boot/files/0003-salvator-x-Don-t-disable-RAVB-module.patch
recipes-domd/domd-image-weston/files/meta-xt-prod-extra/recipes-bsp/u-boot/u-boot_2015.04.bbappend
recipes-domd/domd-image-weston/files/meta-xt-prod-extra/recipes-graphics/wayland/weston_%.bbappend

Don't disable RAVB module before leaving U-Boot

---

recipes-dom0/dom0-image-thin-initramfs/files/meta-xt-prod-extra/recipes-extended/guest-addons/files/domu-salvator-x-h3-4x2g.cfg

domu: Add gsx_domu dtdev node for Salvator X H3 ES3.0

---

recipes-dom0/dom0-image-thin-initramfs/files/meta-xt-prod-extra/recipes-extended/guest-addons/files/doma-salvator-x-h3-4x2g.cfg
recipes-dom0/dom0-image-thin-initramfs/files/meta-xt-prod-extra/recipes-extended/guest-addons/files/doma-salvator-x-h3.cfg
recipes-dom0/dom0-image-thin-initramfs/files/meta-xt-prod-extra/recipes-extended/guest-addons/files/doma-salvator-x-m3.cfg
recipes-dom0/dom0-image-thin-initramfs/files/meta-xt-prod-extra/recipes-extended/guest-addons/files/doma-salvator-xs-h3.cfg
recipes-dom0/dom0-image-thin-initramfs/files/meta-xt-prod-extra/recipes-extended/guest-addons/files/domu-salvator-x-h3-4x2g.cfg
recipes-dom0/dom0-image-thin-initramfs/files/meta-xt-prod-extra/recipes-extended/guest-addons/files/domu-salvator-x-h3.cfg
recipes-dom0/dom0-image-thin-initramfs/files/meta-xt-prod-extra/recipes-extended/guest-addons/files/domu-salvator-x-m3.cfg
recipes-dom0/dom0-image-thin-initramfs/files/meta-xt-prod-extra/recipes-extended/guest-addons/files/domu-salvator-x-m3n.cfg

Use "unique-id" instead of "id" since unique display
connector identifier was added.

Update domain configuration files

---

recipes-domu/domu-image-android/files/meta-xt-prod-extra/recipes-extended/android/android.bbappend

Switch prod-devel to Android Pie

Switch DomA manifest to Android based on android-9.0.0_r3 version

---

recipes-dom0/dom0-image-thin-initramfs/files/meta-xt-prod-extra/recipes-extended/guest-addons/files/doma-salvator-x-h3-4x2g.cfg
recipes-dom0/dom0-image-thin-initramfs/files/meta-xt-prod-extra/recipes-extended/guest-addons/files/doma-salvator-x-h3.cfg
recipes-dom0/dom0-image-thin-initramfs/files/meta-xt-prod-extra/recipes-extended/guest-addons/files/doma-salvator-x-m3.cfg
recipes-dom0/dom0-image-thin-initramfs/files/meta-xt-prod-extra/recipes-extended/guest-addons/files/doma-salvator-xs-h3.cfg

Setup sound backend to use pulse instead of alsa on XS board (this fixes audio quality issue).
Add audio capture device for DomA on all boards.

Change vsnd settings for doma.cfg

---

doc/mk_sdcard_image.sh

* Changed behavior of interacting with the external device.
All devices/files will be processed using loop device(this done
for predictable access to the 4-th partition, since in block
devices it can be named as /dev/sd*4 and /dev/mmcblk*p4).
* Fixed file mode
* Sparced inflation
* Set fixed 4-th partition size
* Added DD progress

mk_sdcard_image: Functional update

---

recipes-domu/domu-image-android/files/meta-xt-prod-extra/recipes-extended/android/android.bbappend

Add functionality and environment variables to make possible
to build Android with pre compiled kernel and graphic.

Build Android with pre compiled binaries

---

INSTALL.txt

Added description fro DomD prebuilts using
XT_RCAR_EVAPROPRIETARY_DIR variable.

Added description for DomD prebuilts

---

doc/uirfs.sh

Fix typo in message

---

doc/mk_sdcard_image.sh

Some improvements for script:
- remove flood messages
- optimize usage of losetup
- redefine hard coded variable

Rework mk_sdcard_image script

---

recipes-domd/domd-image-weston/files/meta-xt-prod-extra/recipes-extended/xen/files/0001-ipmmu-vmsa-Disable-CONFIG_RCAR_IPMMU_PGT_IS_SHARED.patch

xen: rebase in-yocto patch onto the current HEAD

---

INSTALL.txt

Updated build prerequisites.Described possibility
to build from the source.

Clarify INSTALL file according to the current state

---

recipes-dom0/dom0-image-thin-initramfs/files/meta-xt-prod-extra/recipes-extended/guest-addons/doma.bb

* Add support for XS 8GB
* Use generic.cfg as default for all boards

doma: Add support for XS 8GB

---

recipes-domu/domu-image-android/files/meta-xt-prod-extra/recipes-extended/android/android.bbappend

doma: Switch to 1.0 release branch

---

INSTALL.txt

Describe convenient "--branch" parameter in INSTALL.txt file

---

recipes-domu/domu-image-android/files/meta-xt-prod-extra/recipes-extended/android/android.bbappend

doma: Switch Android to 9.0.0_r3-master branch

---

recipes-domd/domd-image-weston/files/meta-xt-prod-extra/recipes-extended/xen/xen_git.bbappend

Signed-off-by: Volodymyr Babchuk <volodymyr_babchuk@epam.com>

xen: enable OP-TEE mediator

---

recipes-domu/domu-image-android/files/meta-xt-prod-extra/recipes-extended/android/android.bbappend

doma: Switch Android to 9.0.0_r3-xt2.0 branch

---

recipes-domd/domd-image-weston/files/meta-xt-prod-extra/recipes-extended/xen/xen_git.bbappend

Signed-off-by: Volodymyr Babchuk <volodymyr_babchuk@epam.com>

xen: use xt_defconfig as a default configuration

---

recipes-domu/domu-image-android/files/meta-xt-prod-extra/recipes-extended/android/android.bbappend

This reverts commit e8911ce42adc5abf27fcf8c78262bca1ea5e5a2f.

Revert "doma: Switch Android to 9.0.0_r3-xt2.0 branch"

---

recipes-domd/domd-image-weston/files/meta-xt-prod-extra/recipes-graphics/wayland/weston_%.bbappend

Boneheaded-by: Oleksandr Andrushchenko <oleksandr_andrushchenko@epam.com>

domd: Simplify weston do_install handling

---

recipes-domd/domd-image-weston/files/meta-xt-prod-extra/recipes-graphics/wayland/weston_%.bbappend

Suggested-by: Ruslan Shymkevych <ruslan_shymkevych@epam.com>

domd: Extract common code in weston do_install code

---

recipes-domu/domu-image-android/files/meta-xt-prod-extra/recipes-extended/android/android.bbappend

domu: switch Android to branch android-9.0.0_r3-xt3.0

---

inc/xen-version.inc

domd/dom0: switch Xen to use branch pv_camera

---

recipes-domd/domd-image-weston/files/meta-xt-prod-extra/recipes-extended/camerabe/camerabe_git.bbappend

Suggested-by: Iurii Artemenko <iurii_artemenko@epam.com>

Fix RDEPENDS for camerabe

---

recipes-domd/domd-image-weston/files/meta-xt-prod-extra/recipes-bsp/alsa-state/files/asound.state
recipes-domd/domd-image-weston/files/meta-xt-prod-extra/recipes-kernel/linux/linux-renesas_%.bbappend

Fix use of AK4613 soundcard on StarterKit

---

doc/mk_sdcard_image.sh

New features of 1.3:
* create DomA with 6 partitions (affects key storage)
* added checks for possible user mistakes

mk_sdcard_image: upgrade version to 1.3

---

recipes-domd/domd-image-weston/files/meta-xt-prod-extra/recipes-core/packagegroups/packagegroup-xt-core-pv.bb
recipes-domd/domd-image-weston/files/meta-xt-prod-extra/recipes-extended/displaymanager/displaymanager_git.bbappend
recipes-domd/domd-image-weston/files/meta-xt-prod-extra/recipes-extended/displaymanager/files/display_manager.conf
recipes-domd/domd-image-weston/files/meta-xt-prod-extra/recipes-extended/guest-addons/files/display-manager.service
recipes-domd/domd-image-weston/files/meta-xt-prod-extra/recipes-extended/guest-addons/guest-addons.bb
recipes-domd/domd-image-weston/files/meta-xt-prod-extra/recipes-graphics/images/core-image-weston.bbappend
recipes-domd/domd-image-weston/files/meta-xt-prod-extra/recipes-graphics/wayland/weston-conf.bbappend
recipes-domd/domd-image-weston/files/meta-xt-prod-extra/recipes-graphics/wayland/weston-init.bbappend
recipes-domd/domd-image-weston/files/meta-xt-prod-extra/recipes-graphics/wayland/weston/weston-seats-kf.rules
recipes-domd/domd-image-weston/files/meta-xt-prod-extra/recipes-multimedia/pulseaudio/files/daemon.conf
recipes-domd/domd-image-weston/files/meta-xt-prod-extra/recipes-multimedia/pulseaudio/files/hifi
recipes-domd/domd-image-weston/files/meta-xt-prod-extra/recipes-multimedia/pulseaudio/files/pulseaudio-bluetooth.conf
recipes-domd/domd-image-weston/files/meta-xt-prod-extra/recipes-multimedia/pulseaudio/files/pulseaudio-ofono.conf
recipes-domd/domd-image-weston/files/meta-xt-prod-extra/recipes-multimedia/pulseaudio/files/pulseaudio.service
recipes-domd/domd-image-weston/files/meta-xt-prod-extra/recipes-multimedia/pulseaudio/files/pulseaudio.socket
recipes-domd/domd-image-weston/files/meta-xt-prod-extra/recipes-multimedia/pulseaudio/files/rsnddai0ak4613h.conf
recipes-domd/domd-image-weston/files/meta-xt-prod-extra/recipes-multimedia/pulseaudio/files/system.pa
recipes-domd/domd-image-weston/files/meta-xt-prod-extra/recipes-multimedia/pulseaudio/files/system_h3ulcb-4x2g-kf-xt.pa
recipes-domd/domd-image-weston/files/meta-xt-prod-extra/recipes-multimedia/pulseaudio/pulseaudio_%.bbappend

This PR contains fixes and updates for KF board.

KF board updates

---

INSTALL.txt

* Add missing packages.
* Wrap few lines that are too long to read on github.

Minor changes to INSTALL.txt

---

doc/u-boot-env.txt

Describe settings for bootloaders from eMMC or HyperFlash

---

recipes-dom0/dom0-image-thin-initramfs/files/meta-xt-prod-extra/recipes-extended/guest-addons/files/domd-h3ulcb-4x2g-kf.cfg
recipes-domd/domd-image-weston/domd-image-weston.bbappend
recipes-domd/domd-image-weston/files/0001-linux-renesas-Remove-patch-230-from-renesas.scc.patch
recipes-domd/domd-image-weston/files/meta-xt-prod-extra/recipes-devtools/clang/compiler-rt_git.bbappend
recipes-domd/domd-image-weston/files/meta-xt-prod-extra/recipes-devtools/clang/libcxx_git.bbappend
recipes-domd/domd-image-weston/files/meta-xt-prod-extra/recipes-graphics/images/core-image-weston.bbappend
recipes-domd/domd-image-weston/files/meta-xt-prod-extra/recipes-kernel/kernel-module-gles/kernel-module-gles/0001-Update-xen_back-DMA-tweaks.patch
recipes-domd/domd-image-weston/files/meta-xt-prod-extra/recipes-kernel/kernel-module-gles/kernel-module-gles_1.10.bbappend
recipes-domd/domd-image-weston/files/meta-xt-prod-extra/recipes-kernel/linux/linux-renesas/0001-Update-gntdev-drm_front-DMA-tweaks.patch
recipes-domd/domd-image-weston/files/meta-xt-prod-extra/recipes-kernel/linux/linux-renesas/r8a7795-h3ulcb-4x2g-kf-dom0.dts
recipes-domd/domd-image-weston/files/meta-xt-prod-extra/recipes-kernel/linux/linux-renesas_%.bbappend

[WIP] Kingfisher follow-up patches

---

INSTALL.txt

Update info regarding DomA partitions.
Rework example of losetup usage.

INSTALL.txt: update info about partitions

---

inc/xen-version.inc

Switch to Xen v4.13 release branch

---

recipes-dom0/dom0-image-thin-initramfs/files/meta-xt-prod-extra/recipes-extended/guest-addons/files/doma-generic-h3-4x2g.cfg
recipes-dom0/dom0-image-thin-initramfs/files/meta-xt-prod-extra/recipes-extended/guest-addons/files/doma-generic-h3.cfg
recipes-dom0/dom0-image-thin-initramfs/files/meta-xt-prod-extra/recipes-extended/guest-addons/files/domd-h3ulcb-4x2g-kf.cfg
recipes-dom0/dom0-image-thin-initramfs/files/meta-xt-prod-extra/recipes-extended/guest-addons/files/domd-h3ulcb-4x2g.cfg
recipes-dom0/dom0-image-thin-initramfs/files/meta-xt-prod-extra/recipes-extended/guest-addons/files/domd-h3ulcb.cfg
recipes-dom0/dom0-image-thin-initramfs/files/meta-xt-prod-extra/recipes-extended/guest-addons/files/domd-m3ulcb.cfg
recipes-dom0/dom0-image-thin-initramfs/files/meta-xt-prod-extra/recipes-extended/guest-addons/files/domd-salvator-x-h3-4x2g.cfg
recipes-dom0/dom0-image-thin-initramfs/files/meta-xt-prod-extra/recipes-extended/guest-addons/files/domd-salvator-x-h3.cfg
recipes-dom0/dom0-image-thin-initramfs/files/meta-xt-prod-extra/recipes-extended/guest-addons/files/domd-salvator-x-m3.cfg
recipes-dom0/dom0-image-thin-initramfs/files/meta-xt-prod-extra/recipes-extended/guest-addons/files/domd-salvator-xs-h3-4x2g.cfg
recipes-dom0/dom0-image-thin-initramfs/files/meta-xt-prod-extra/recipes-extended/guest-addons/files/domd-salvator-xs-h3.cfg
recipes-dom0/dom0-image-thin-initramfs/files/meta-xt-prod-extra/recipes-extended/guest-addons/files/domx-pvcamera.cfg
recipes-domd/domd-image-weston/files/meta-xt-prod-extra/recipes-extended/camerabe/camerabe_git.bbappend
recipes-domd/domd-image-weston/files/meta-xt-prod-extra/recipes-extended/camerabe/files/camera_be.cfg
recipes-domd/domd-image-weston/files/meta-xt-prod-extra/recipes-extended/camerabe/files/camerabe.service

Please note that the following patches are not for review, just for possibility to build and test: 
- [DO NOT MERGE] Enable PV Camera support
- [DO NOT MERGE] Switch to local repo until camera_be is not merged
Corresponding PR https://github.com/xen-troops/camera_be/pull/9

MC-enabled PV camera backend and "HDMI_IN camera" integration

---

doc/mk_sdcard_image.sh

* Upgrade version to reflect latest changes.
* Check for android related tool only if android is a guest.

Update mk_sdcard_image script

---

recipes-domd/domd-image-weston/files/meta-xt-prod-extra/recipes-bsp/u-boot/files/0001-pci-renesas-Add-RCar-Gen3-PCIe-controller-driver.patch
recipes-domd/domd-image-weston/files/meta-xt-prod-extra/recipes-bsp/u-boot/files/0002-Enable-PCI-related-configs.patch
recipes-domd/domd-image-weston/files/meta-xt-prod-extra/recipes-bsp/u-boot/files/0003-Fix-missing-MACCTLR-register-setting-in-initializati.patch
recipes-domd/domd-image-weston/files/meta-xt-prod-extra/recipes-bsp/u-boot/u-boot_2018.09.bbappend
recipes-domd/domd-image-weston/files/meta-xt-prod-extra/recipes-kernel/linux/linux-renesas/r8a7795-salvator-x-4x2g-dom0.dts
recipes-domd/domd-image-weston/files/meta-xt-prod-extra/recipes-kernel/linux/linux-renesas/r8a7795-salvator-x-4x2g-domd.dts
recipes-domd/domd-image-weston/files/meta-xt-prod-extra/recipes-kernel/linux/linux-renesas/r8a7795-salvator-xs-4x2g-dom0.dts
recipes-domd/domd-image-weston/files/meta-xt-prod-extra/recipes-kernel/linux/linux-renesas/r8a7795-salvator-xs-4x2g-domd.dts

Please note, PCI is enabled in U-Boot for salvator-x-h3-4x2g only

PCI misc updates

---

INSTALL.txt

DDK 1.11 has specific binaries setup. Update INSTALL.txt
with respect to it.

doma: Update INSTALL.txt with respect to DDK 1.11

---

recipes-domu/domu-image-android/files/meta-xt-prod-extra/recipes-extended/android/android.bbappend

doma: Switch to fixed Android 11 release REL-v5.0

---

INSTALL.txt

Update INSTALL.txt with new doma partition  scheme

---

recipes-dom0/dom0-image-thin-initramfs/files/meta-xt-prod-extra/recipes-bsp/u-boot/u-boot_%.bbappend

The revision has been updated to include the bug-fix of RPM emulator.

u-boot: fix bug in RPM emulator

---

recipes-emu/qemu/files/qemu-run-zynqmp-xilinx-xen.sh

QEMU script

---

inc/xen-version.inc

Signed-off-by:Oleksandr Tyshchenko <oleksandr_tyshchenko@epam.com>

xen access

---

recipes-domd/domd-image-weston/files/meta-xt-prod-extra/recipes-aos/aos-vis/aos-vis_git.bbappend

do_unpuck: typo, must be do_unpack

---

doc/u-boot-env.txt

Signed-off-by: Yevgen Abramov <Yevgen_Abramov@epam.com>
Reviewed-by: Oleksandr Tyshchenko <oleksandr_tyshchenko@epam.com>

u-boot-env.txt: Add note for enabling of booting SoC from the eMMC

---

recipes-domd/domd-image-weston/files/0001-Add-vspfilter-configs.patch

This commit fixes gstreamer video playback issue using vspfilter.
Update commit:
89892c12d8f479865cdfa96e2515d7fd293b6c4e
domd: Update vspfilter configs for "h3ulcb" based machines
Signed-off-by: Valerii Chubar <valerii_chubar@epam.com>

domd: Fix vspfilter configs for "h3ulcb" based machines

---

recipes-domd/domd-image-weston/files/meta-xt-prod-extra/recipes-aos/aos-vis/aos-vis_git.bbappend

We need to modify config before it will be packed.

domd: aos: Run do_configure_adapters before do_package
