xen-troops/meta-xt-prod-devel

recipes-dom0/dom0-image-weston/files/meta-xt-prod-extra/recipes-graphics/images/core-image-weston.bbappend
recipes-dom0/dom0-image-weston/files/meta-xt-prod-extra/recipes-graphics/images/dom0-image-weston-domu-copy-kernel.bb
recipes-domu/domu-image-weston/files/meta-xt-prod-extra/recipes-graphics/gles-module/files/72-pvr-seat.rules.patch
recipes-domu/domu-image-weston/files/meta-xt-prod-extra/recipes-graphics/gles-module/gles-user-module.bbappend
recipes-domu/domu-image-weston/files/meta-xt-prod-extra/recipes-graphics/images/core-image-weston.bbappend
recipes-domu/domu-image-weston/files/meta-xt-prod-extra/recipes-kernel/kernel-module-gles/kernel-module-gles.bbappend

Fixes:
- build pvr kernel module from Xen-troops sources, not from default uri
- force DomU kernel to be always installed
- fix udev rule for DomU's pvr km: weston seat
Added:
- kmscube

fixes and improvements

---

recipes-dom0/dom0-image-weston/files/meta-xt-prod-extra/recipes-extended/guest-addons/files/domu.cfg

Instead of using DomU kernel from /boot/domu Dom0's
kernel was used to boot DomU from /boot.

Fix: really use DomU kernel

---

recipes-dom0/dom0-image-weston/files/meta-xt-prod-extra/recipes-extended/xen/xen_git.bbappend

During Xen deployment symlinks are created with absolute path
instead of relative for xen-uImage and xenpolicy.

Fix absolute paths for Xen symlinks

---

recipes-dom0/dom0-image-weston/dom0-image-weston.bbappend
recipes-dom0/dom0-image-weston/files/meta-xt-prod-extra/conf/bblayers.conf.sample
recipes-domu/domu-image-weston/domu-image-weston.bbappend
recipes-domu/domu-image-weston/files/meta-xt-prod-extra/conf/bblayers.conf.sample

Make "dom0" and "domU" use separate manifest files.
Exclude "meta-virtualization" and "meta-selinux" layers
from "domU" image build.

Odd layers for DomU build.

---

recipes-dom0/dom0-image-weston/files/meta-xt-prod-extra/recipes-kernel/linux/linux-renesas/r8a7796-salvator-x-dom0.dts
recipes-dom0/dom0-image-weston/files/meta-xt-prod-extra/recipes-kernel/linux/linux-renesas/r8a7796-salvator-x-domu.dts
recipes-dom0/dom0-image-weston/files/meta-xt-prod-extra/recipes-kernel/linux/linux-renesas_%.bbappend

Dom0's dts is based on v4.9/rcar-3.5.3 device tree for Salvator-X M3 board.
DomU's dts is a copy of r8a7795-salvator-x-domu.dts.
WARNING: dts files are only compile tested wrt IOMMU support!!!

Add Dom0/U dts files for Salvator-X M3

---

recipes-domd/agl/files/meta-xt-prod-extra/recipes-kernel/linux/linux-renesas/r8a7795-salvator-x-dom0.dts
recipes-domd/agl/files/meta-xt-prod-extra/recipes-kernel/linux/linux-renesas/r8a7795-salvator-x-domd.dts
recipes-domd/agl/files/meta-xt-prod-extra/recipes-kernel/linux/linux-renesas/r8a7796-salvator-x-dom0.dts
recipes-domd/agl/files/meta-xt-prod-extra/recipes-kernel/linux/linux-renesas/r8a7796-salvator-x-domd.dts

This hint is not needed anymore. With corresponding support in Xen
the A3VP power domain as well as other non ALWAYS_ON domains
some IPMMU caches belong to are turned on in advance.
Reviewed-by: Andrii Anisov <andrii_anisov@epam.com>

dom0.dts/domd.dts: Remove "power-domains" property from SDHI2 node

---

recipes-dom0/dom0-image-thin-initramfs/dom0-image-thin-initramfs.bbappend

Unfortunately a missprint sneaked into the previous patch, so it should be fixed to get it functional.

dom0: fix passing XT_GUESTS_INSTALL into lower yocto build

---

recipes-domd/agl/files/meta-xt-prod-extra/recipes-graphics/wayland/weston/weston-seats.rules

Remove vendor and device ID hardcode from weston seats rules, also
add more wildcards to USB device pathes in order to get the setup
portable to a different setup configuration.

domd: weston seats harcode clenup

---

recipes-dom0/dom0-image-rescue-initramfs/dom0-image-rescue-initramfs.bbappend
recipes-dom0/dom0-image-thin-initramfs/dom0-image-thin-initramfs.bbappend
recipes-domd/domd-image-weston/domd-image-weston.bbappend
recipes-domd/domd-image-weston/files/meta-xt-prod-extra/recipes-extended/domd-install-machine-overrides/domd-install-machine-overrides.bb
recipes-domd/domd-image-weston/files/meta-xt-prod-extra/recipes-graphics/images/core-image-weston.bbappend
recipes-domu/domu-image-android/domu-image-android.bbappend

1. do_fetch can be started in parallel for all domains
2. No need for DomD to be build to the end and produce machine overrides,
this can be done sooner. Thus, allow DomA to start building sooner.
Note: domd-install-machine-override recipe is implemented as a native
one, thus there is still room to optimize that: native recipes make
Yocto build some native dependencies, but for domd-install-machine-override
those are not needed. Removing such a dependency will allow providing
overrides before building the required native packages (470 at the moment).
Those will still be used during the domain build, but providing
overrides sooner means running DomA build sooner.

Speedup build by rearranging build dependencies

---

recipes-domd/domd-image-weston/files/meta-xt-prod-extra/recipes-extended/sensors-emulator/sensors-emulator.bb

Sensors emulator needs socketserver module. So add a netserv package
which includes socketserver to the system.

Fix to get sensors-emulator running in DomD

---

recipes-domd/domd-image-weston/files/meta-xt-prod-extra/recipes-extended/guest-addons/files/display-manager.service
recipes-domd/domd-image-weston/files/meta-xt-prod-extra/recipes-extended/guest-addons/files/displbe.service

Both displbe and display-manager are dependent on weston to get run.
Due to the fact that we do not have them implemented as daemons yet,
we should get a check on weston availability first in order to avoid
nasty races in the system. Use weston-info as a checker for now.
4 seconds timeout is enough to get it started from SD card and do not
hit restart rate threshold.

Set an explicit dependency on weston for displbe and display-manager

---

recipes-dom0/dom0-image-thin-initramfs/files/meta-xt-prod-extra/recipes-core/images/core-image-thin-initramfs.bbappend

While checking for wich doamain artifact must be installed
the default values must be weak, so one can override the
default settings.
Fixes: d8b048c11692 ("Explicitly add XT_GUESTS_INSTALL variable into the recipe")

dom0: Fix installed domain artifacts

---

recipes-domd/domd-image-weston/files/meta-xt-prod-extra/recipes-kernel/linux/linux-renesas_%.bbappend

Device tree names must be provided as .dtb, not .dts,
so those are built with the kernel.
Fixes: 8fe2a7da1c81 ("Add Salvator-X M3 device trees to the kernel build")

domd: Fix Salvator-X M3 device tree build

---

recipes-domd/domd-image-weston/files/meta-xt-prod-extra/recipes-graphics/wayland/weston_%.bbappend

Make a proper check if XT_GUESTS_INSTALL environment variable is set.

domd: Fix error if XT_GUESTS_INSTALL is not set

---

recipes-domd/domd-image-weston/domd-image-weston.bbappend

For DomU based product we want plain Weston without IVI
extensions.

domd: Do not use ivi-shell for DomU based product

---

recipes-domd/domd-image-weston/files/meta-xt-prod-extra/recipes-graphics/wayland/weston_%.bbappend

DomU based product doesn't need Weston to rotate VGA-1 connector
to 270 degrees.

domd: Do not rotate Weston on VGA-1 for DomU product

---

recipes-domd/domd-image-weston/files/meta-xt-prod-extra/recipes-graphics/rcar-proprietary-graphic/prepare-graphic-package.bb
recipes-domd/domd-image-weston/files/meta-xt-prod-extra/recipes-graphics/rcar-proprietary-graphic/rcar-proprietary-graphic.bb

Fix RCAR proprietary DDK archive names to contain "domd"
instead of "domu".

domd: Fix RCAR proprietary DDK archive names

---

recipes-domd/domd-image-weston/files/meta-xt-prod-extra/recipes-graphics/rcar-proprietary-graphic/rcar-proprietary-graphic.bb
recipes-domu/domu-image-weston/files/meta-xt-prod-extra/recipes-graphics/rcar-proprietary-graphic/rcar-proprietary-graphic.bb

While preparing archives with the graphics DDK binaries we use
${MACHINE} based archive names in SRC_URI while using external
binaries with graphics later we open code those. Fix this by
making rcar-proprietary-graphic recipe use the same approach
as prepare-graphic-package does.

domd/domu: Use unified name for proprietary DDK binaries

---

recipes-domd/domd-image-weston/domd-image-weston.bbappend
recipes-domd/domd-image-weston/files/meta-xt-prod-extra/recipes-graphics/rcar-proprietary-graphic/rcar-proprietary-graphic.bb
recipes-domu/domu-image-weston/domu-image-weston.bbappend
recipes-domu/domu-image-weston/files/meta-xt-prod-extra/recipes-graphics/rcar-proprietary-graphic/rcar-proprietary-graphic.bb

When DDK is provided in a binary form, e.g. is not built from
sources, the dependency for GLES headers is still the sources.
Fix this by making binary package the provider of the headers.

domd/domu: Fix GLES header dependency for provided DDK

---

recipes-domd/domd-image-weston/files/meta-xt-prod-extra/recipes-graphics/images/core-image-weston.bbappend

packagegroup-graphics-renesas-proprietary is about to be used
to pack graphics DDK binaries into an archive, but it is not
intended to be installed into the final image.

domd: Do not try installing packagegroup-graphics-renesas-proprietary

---

recipes-domd/domd-image-weston/files/meta-xt-prod-extra/recipes-kernel/linux/linux-renesas_%.bbappend

Build DomU device tree for Salvator-X H3 ES2.0 from
Salvator-X H3 ES3.0 as those are identical.

domd: Build DomU device tree for Salvator-X H3 ES2.0

---

recipes-domd/domd-image-weston/files/meta-xt-prod-extra/recipes-extended/displbe/displbe_git.bbappend

If Weston is built without ivi-shell there is no point to build
the backend with IVI extensions.

domd: Do not build displbe with IVI extensions if no ivi-shell

---

recipes-domd/domd-image-weston/files/meta-xt-prod-extra/recipes-extended/displbe/displbe_git.bbappend

This reverts commit 8126ad7f745628f3c8c41b639aabd238d4bac9bf.
The commit does break the default prod-devel build.

Revert "domd: Do not build displbe with IVI extensions if no ivi-shell"

---

recipes-domd/domd-image-weston/files/meta-xt-prod-extra/recipes-extended/libconfig/libconfig_1.5.bbappend

libconfig v1.5 does not contain CMake file, so avoid using cmake.
Also inheritance of autotools-brokensep and pkgconfig is already
in original recipe, so cleanup double inheritance.

Fix libconfig recipe

---

recipes-dom0/dom0-image-thin-initramfs/files/meta-xt-prod-extra/recipes-kernel/linux/linux-generic-armv8.bbappend
recipes-domd/domd-image-weston/files/meta-xt-prod-extra/recipes-kernel/linux-libc-headers/linux-libc-headers_%.bbappend
recipes-domd/domd-image-weston/files/meta-xt-prod-extra/recipes-kernel/linux/linux-renesas_%.bbappend
recipes-domu/domu-image-fusion/files/meta-xt-prod-extra/recipes-kernel/linux/linux-generic-armv8.bbappend
recipes-domu/domu-image-weston/files/meta-xt-prod-extra/recipes-kernel/linux-libc-headers/linux-libc-headers_%.bbappend
recipes-domu/domu-image-weston/files/meta-xt-prod-extra/recipes-kernel/linux/linux-renesas_%.bbappend

Assign LINUX_VERSION in the current product`s recipes so commit
7d7ffd91787ea89196c1664ff48bf5fd98370cec can be reverted from
meta-xt-images layer.

Set Linux kernel version to 4.14.35

---

doc/mk_sdcard_image.sh

Add waiting for block device, to be sure that it is accessible
by losetup.

Wait for device to be accessible

---

recipes-domd/domd-image-weston/files/meta-xt-prod-extra/recipes-bsp/alsa-state/files/asound.state

Enable audio input by setting input volume to 80% of max.

Set default volume for audio record

---

doc/mk_sdcard_image.sh

Add check that domains exist in deploy path.
This check is needed as protection against possible misuses.
Misuse 1. If specified deploy path is higher than actually needed, then script will find all kernel images and write them to dom0.
Misuse 2. If deploy path has no domu, script will quit and will left loop device hanging.
Also two minor fixes for misprint and default image size.

Add check of doms

---

recipes-domu/domu-image-android/files/meta-xt-prod-extra/recipes-extended/android/android.bbappend

Add missed link to uncompressed kernel to shared folder
to let Dom0 use it.

Fix missed link to kernel

---

recipes-domu/domu-image-android/files/meta-xt-prod-extra/recipes-extended/android/android.bbappend

Yocto`s default patch tool 'quilt' duplicates pathed file,
in this case Android.bp, which causing ninja compiler to failure.
So, we have to use 'git' as a patch tool.

Change default patch tool

---

recipes-domd/domd-image-weston/files/meta-xt-prod-extra/recipes-kernel/linux/linux-renesas/r8a7795-salvator-x-4x2g-domd.dts

Just removing the highest HS400 mode for eMMC avoids read/write
errors on a heavy loads.
Tested-by: Andrii Chepurnyi <andrii_chepurnyi@epam.com>

r8a7795-salvator-x-4x2g-domd: Try to low SD/EMMC speed

---

recipes-domd/domd-image-weston/domd-image-weston.bbappend
recipes-domu/domu-image-weston/domu-image-weston.bbappend

Add function to transform product name to manifest
folder name substituting hyphen with underscore.
Cherry-picked from gen3-test product with minor alignment (default product name).
Reviewed-by: Oleksandr Andrushchenko <oleksandr_andrushchenko@epam.com>

Add manifest folder name

---

recipes-dom0/dom0-image-thin-initramfs/files/meta-xt-prod-extra/recipes-extended/guest-addons/files/doma-salvator-generic.cfg
recipes-dom0/dom0-image-thin-initramfs/files/meta-xt-prod-extra/recipes-extended/guest-addons/files/doma-salvator-x-h3-4x2g.cfg

Separate playback devices are provided for support of Android's
automotive audio buses.
For now we can have max 8 buses (media, navi, radio, etc).

Provide 8 playback devices for all devices

---

recipes-domd/domd-image-weston/files/meta-xt-prod-extra/recipes-kernel/linux/linux-renesas_%.bbappend

Fix for 7e2d1d1c "Unite *-doma.dts".
DTB was renamed for SRC_URI_XXX, but not for KERNEL_DEVICETREE_XXX.
Also fix erroneously missed DTB for few boards.

Fix usage of .dtb for doma

---

recipes-domd/domd-image-weston/files/meta-xt-prod-extra/doc/local.conf.rcar-domd-image-weston

Enable Weston V4L2 renderer, which runs using VSPM device.
This change:
1. Enables vsp2/vspm kernel modules
2. Appends "--use-v4l2" argument to weston-launch/weston
3. Makes weston use v4l2 renderer

domd: Enable Weston V4L2 renderer

---

recipes-domd/domd-image-weston/files/meta-xt-prod-extra/recipes-extended/libconfig/libconfig_1.5.bbappend
recipes-domd/domd-image-weston/files/meta-xt-prod-extra/recipes-graphics/wayland/wayland-ivi-extension_2.0.0.bbappend

wayland-ivi-extension, libconfig:
Due to build system conflicts we have to set commit hash
or tag in SRCREV instead of SRC_URI in order
to use build reconstruction functionality.

Remove tag from SRC_URI

---

doc/mk_sdcard_image.sh

Due to mistake total size of image was calculated after it's usage.
Now DEFAULT_IMAGE_SIZE_GIB is calculated before inflate_image().

Fix writing of image into file

---

doc/mk_sdcard_image.sh

What's updated in script:
* Added support for AOS and Gen3-Test.
* Added command line option -f for forced inflation of image in case of automated usage.
* Partition's number and label is described inside configuration for each product.
* Reduced number of used loop devices, now we create one 'upper' level loop device for writing of full image, and one loop device for writing of android's image, if needed.
* Reduced number of variables created by script.
* Version increased to 1.2.
Tests.
Script was tested for all supported products: aos, ces2019, devel and gen3.
Tested functionality:
* creation of image file
* update of user's domain inside existing image (-u)
* check that created image starts on HW: for ces2019, devel and gen3. For aos - just check size of image file.

mk_sdcard_image: Add support for prod-aos and prod-gen3-test

---

inc/xen-version.inc
recipes-dom0/dom0-image-thin-initramfs/dom0-image-thin-initramfs.bbappend
recipes-dom0/dom0-image-thin-initramfs/files/meta-xt-prod-extra/recipes-extended/xen/xen_git.bbappend
recipes-domd/domd-image-weston/domd-image-weston.bbappend
recipes-domd/domd-image-weston/files/meta-xt-prod-extra/recipes-extended/xen/xen_git.bbappend

Unify XEN version for Dom0 and DomD in one include file and use an appropriate glue file for the yocto version. This requires the XEN include file change from [meta-xt-images](https://github.com/xen-troops/meta-xt-images/pull/109).

Unify XEN version for Dom0 and DomD

---

recipes-domd/domd-image-weston/files/meta-xt-prod-extra/recipes-graphics/wayland/weston_%.bbappend

In order to adopt the latest fix for dma-buf release, we have to use an
appropriate code base version. So promote weston's SRCREV to the current
HEAD of the taken branch.

domd:weston: promote weston sources revision

---

INSTALL.txt
recipes-domd/domd-image-weston/domd-image-weston.bbappend

Script mk_sdcard_image_domu.sh is superseded by mk_sdcard_image.sh
This two patches fix references to absent script.

Fix references to obsolete script

---

inc/xen-version.inc
recipes-dom0/dom0-image-thin-initramfs/dom0-image-thin-initramfs.bbappend
recipes-dom0/dom0-image-thin-initramfs/files/meta-xt-prod-extra/recipes-extended/xen/files/0001-libxl-Add-DTB-compatible-list-to-config-file.patch
recipes-dom0/dom0-image-thin-initramfs/files/meta-xt-prod-extra/recipes-extended/xen/files/0002-libxl-Add-DTB-passthrough-nodes-list.patch
recipes-dom0/dom0-image-thin-initramfs/files/meta-xt-prod-extra/recipes-extended/xen/xen_git.bbappend
recipes-domd/domd-image-weston/domd-image-weston.bbappend
recipes-domd/domd-image-weston/files/meta-xt-prod-extra/recipes-extended/xen/xen_git.bbappend
recipes-domd/domd-image-weston/files/meta-xt-prod-extra/recipes-kernel/linux/linux-renesas/xen-chosen.dtsi

Please note, here we have still adopted xen_git.bbappend from meta-xt-images. Switching to .inc files should be done as a separate task.

Xen 4.12rc migration

---

recipes-dom0/dom0-image-thin-initramfs/files/meta-xt-prod-extra/recipes-extended/guest-addons/files/domd-salvator-x-m3.cfg

With i2c_dvfs being assigned to domd, interrupt-controller@e61c0000
mem range must be accessible here as well.

Add missed interrupt-controller mem range to m3 domain cfg file

---

recipes-domd/domd-image-weston/files/meta-xt-prod-extra/recipes-extended/xen/xen_git.bbappend

In order to not change xen bbappends in case of XEN minor versions
or -rc changes, wildcard the xenpolicy file name tail.
This will work under normal build conditions, might fail in case we
eventually, have several xenpolicy files in the folder (what is
assumed as abnormal).
Reviewed-by: Oleksandr Andrushchenko <oleksandr_andrushchenko@epam.com>
Reviewed-by: Oleksandr Tyshchenko <oleksandr_tyshchenko@epam.com>

domd:xen: Wildcard minor XEN version in xenpolicy file name

---

recipes-dom0/dom0-image-thin-initramfs/files/meta-xt-prod-extra/recipes-extended/guest-addons/files/doma-salvator-x-h3-4x2g.cfg

Doma memory was reduced due to issue:
vdispl vdispl-0: DMA: Out of SW-IOMMU space for 1048576 bytes
pvrsrvkm fd000000.gsx: DMA: Out of SW-IOMMU space for 1048576 bytes
Appropriate fixes were merged an we can place back 6GB.

doma: Provide 6GB to doma for salvator-x-h3-4x2g machine

---

recipes-domd/domd-image-weston/files/meta-xt-prod-extra/recipes-graphics/images/core-image-weston.bbappend

telemetry-emulator is added conditionally and should be removed from
the append list.
Signed-off-by: Oleksandr Grytsov <oleksandr_grytsov@epam.com>

domd: remove telemetry-emulator from IMAGE_INSTALL_append

---

recipes-domd/domd-image-weston/files/meta-xt-prod-extra/recipes-aos/aos-vis/aos-vis_git.bbappend
recipes-domd/domd-image-weston/files/meta-xt-prod-extra/recipes-graphics/images/core-image-weston.bbappend

Checking AOS_VIS_PLUGINS in core-image-weston.bbappend is not correct. As
this variable is not defined by default in local config. As result
telemetry-emulator is not installed by default regardless telemetry
emulator adapter is installed. The right solution is to add telemetry-
emulator as RDEPENDS in aos-vis recipe.
Signed-off-by: Oleksandr Grytsov <oleksandr_grytsov@epam.com>

domd: make telemetry-emulator as RDEPENDS of aos-vis

---

recipes-dom0/dom0-image-thin-initramfs/files/meta-xt-prod-extra/recipes-extended/guest-addons/files/doma-salvator-generic.cfg
recipes-dom0/dom0-image-thin-initramfs/files/meta-xt-prod-extra/recipes-extended/guest-addons/files/doma-salvator-x-h3-4x2g.cfg

Android share one device node with op-tee. This results in inability
of Android to properly load device tree. So we have to direct android
to proper location of it's device tree.

op-tee patch set: doma.cfg: Specify android's device tree

---

INSTALL.txt

TARGET_PREBUILT_KERNEL is not obligatory now,
becuse kernel is in opensource and it not set in
meta-xt-images after patch
"doma: Do not propagate TARGET_PREBUILT_KERNEL".

Remove kernel prebuilt from INSTALL.txt

---

recipes-domd/domd-image-weston/domd-image-weston.bbappend

Since we want to redistribute aos-vis as a pre-built
package populate it and dependent package into the deploy
directory while building rootfs image.

domd: populate aos-vis package into the deploy directory

---

INSTALL.txt

In case of prod-devl build, AOS VIS can be installed from a
prebuilt package. AOS_VIS_PACKAGE_DIR should points to directory
with aos-vis_git-r0_aarch64.ipk, ca-certificates_20170717-r0_all.ipk.

Update INSTALL.txt with AOS VIS packages

---

recipes-domd/domd-image-weston/files/meta-xt-prod-extra/recipes-extended/guest-addons/guest-addons.bb

All {H|M}3ULCB boards have single display connector.
Kingfisher has also single display connector.
It's appeared that Salvator-x-h3 config file
works well with kingfisher_r8a7795 board.
Tested both display outputs with DomD and DomA.
Signed-off-by: Viktor Mitin <viktor_mitin@epam.com>

domd: Provide DM config for kingfisher_r8a7795 board

---

recipes-domd/domd-image-weston/files/meta-xt-prod-extra/recipes-graphics/images/core-image-weston.bbappend

Currently 'wireless-tools' which is needed for
h3ulcb-4x2g-kf-xt machine became obsolete so,
supersed it by 'iw' in final rootfs image.

domd: supersede 'wireless-tools' by 'iw' in rootfs image

---

doc/mk_sdcard_image.sh

If dom0/initramfs is unpacked into dom0 subfolder, 'find' will return
all found kernel images and incorrect kernel will be used as dom0 kernel.
This patch prevents such error.

mk_sdcard_image: Check number of found images

---

doc/mk_sdcard_image.sh

If SD card is specified as target, but not plugged into PC,
we will have incorrect situation: file will be created inside /dev folder
with name like /dev/sdc. This error sometimes is hard to clarify.
In order to avoid such confusion we will not create files inside /dev.

mk_sdcard_image: Prevent creation of files inside /dev folder

---

doc/u-boot-env.txt

Combined commits from gen3-test with minor changes:
d578d099 Add instruction how to remove header from tee.bin
42be1ad7 Improve convenience of usage
50719158 Update info related to tee.bin
Combined summary of changes:
Add info regarding network boot.
This patch improves usage of some variables:
* removes boot_dev variable. Each bootcmd now has it's own *_dtb_load
with specific boot device
* added reminders to make easier to remember mapping of bootcmd and
corresponding boot device
* naming of variables for network boot (tftp) changed to be unified
with other devices
* change name of flash_loaders to flash_z_loaders so it will be not
lost inside other flash_* names
For some products build system was updated and there can be found two
binaries of tee.bin - with and without header. …

Update u-boot-env.txt with changes from gen3-test

---

recipes-dom0/dom0-image-thin-initramfs/files/meta-xt-prod-extra/recipes-core/base-files/base-files_%.bbappend
recipes-domd/domd-image-weston/files/meta-xt-prod-extra/recipes-core/base-files/base-files_%.bbappend

"shopt -s checkwinsize" - will change the behaviour of command
placement in shell input. I.e. will not wrap input, but
continue it from the next line if it too big.
"resize" - set environment and terminal settings to current
xterm window size

dom0/domd: enhance editing experience in domain shell

---

recipes-domd/domd-image-weston/files/meta-xt-prod-extra/recipes-extended/guest-addons/files/sndbe.service

sndbe requires proc-xen mount same as displbe service.
Signed-off-by: Oleksandr Grytsov <oleksandr_grytsov@epam.com>

domd: add proc-xen.mount to sndbe.service as requires field

---

recipes-domd/domd-image-weston/files/meta-xt-prod-extra/recipes-multimedia/pulseaudio/files/system.pa

Set pcm3168a as default playback device on Kingfisher.

Set default sink for KF

---

INSTALL.txt
recipes-domd/domd-image-weston/domd-image-weston.bbappend
recipes-domd/domd-image-weston/files/meta-xt-prod-extra/recipes-graphics/images/core-image-weston.bbappend

Generate symbolic links instead of using .ipk files with
hard coded names in recipes because file name might be
dynamically changed depending on date.

domd: Avoid using .ipk files with hardcoded names

---

recipes-domd/domd-image-weston/files/meta-xt-prod-extra/recipes-bsp/alsa-state/files/kingfisher/asound.state

When we build for StarterKit with Kingficher, we use Cogent's device tree.
Cogent use their own name for ak4613 sound card - 'ak4613',
while on other boards it has name 'rcar-sound'.
This affects configuration file used by alsactl for setting of volume levels.
This is why we need dedicated config for SK+KF.

Use dedicated asound.state for SK+KF

---

recipes-domd/domd-image-weston/domd-image-weston.bbappend
recipes-domd/domd-image-weston/files/meta-xt-prod-extra/recipes-graphics/images/core-image-weston.bbappend

When build with DomU we do not use AOS-VIS so conditionally
remove it from rootfs image and meta-layers. Also do not
install AOS-VIS binary package for DomU based product.

domd: Conditionally remove AOS-VIS

---

recipes-dom0/dom0-image-thin-initramfs/files/meta-xt-prod-extra/recipes-extended/dev86/dev86_%.bbappend
recipes-domd/domd-image-weston/files/meta-xt-prod-extra/recipes-extended/dev86/dev86_%.bbappend

Temporary solution until error below is fixed.
This site can’t be reached
v3.sk took too long to respond.
Search Google for sk ~lkundrak dev86 archive Dev86src tar
ERR_CONNECTION_TIMED_OUT

dev86-native: Use github link for SRC_URI

---

recipes-domu/domu-image-weston/files/meta-xt-prod-extra/recipes-core/base-files/base-files_%.bbappend

"shopt -s checkwinsize" - will change the behaviour of command
placement in shell input. I.e. will not wrap input, but
continue it from the next line if it too big.
"resize" - set environment and terminal settings to current
xterm window size
Suggested-by: Viktor Mitin <viktor_mitin@epam.com>

domu: enhance editing experience in domain shell

---

recipes-domd/domd-image-weston/files/meta-xt-prod-extra/recipes-multimedia/pulseaudio/files/kingfisher/system.pa

We used to use udev-detect module to find availabe cards, but this
results in two issues:
1) not predictible order of soundcards
2) sometimes pcm3168a is detected and loaded to slow, and system.pa
script is not able to set it as default.
Patch solves these issues by removing udev-detect and directly loading
alsa-card modules for each sound card. At this point we need to separate
system.pa for SK+KF and other cards, as far as we have only ak4613 on
all boards (salvator-x, -xs, starterkit) exept starterkit with kingfisher
where we have pcm3168a, ak4613, radio and bt. Last two are not used
for now so alsa-card module is not loaded for them.

Use dedicated PulseAudio config for SK_KF and remove udev-detect

---

recipes-domd/domd-image-weston/files/meta-xt-prod-extra/recipes-graphics/images/core-image-weston.bbappend

Conditionally install ca-certificates in case we
install aos-vis as a prebuilt binary.

domd: Add ca-certificates into the rootfs

---

recipes-dom0/dom0-image-thin-initramfs/files/meta-xt-prod-extra/recipes-extended/guest-addons/files/doma-salvator-generic.cfg
recipes-dom0/dom0-image-thin-initramfs/files/meta-xt-prod-extra/recipes-extended/guest-addons/files/doma-salvator-x-h3-4x2g.cfg
recipes-dom0/dom0-image-thin-initramfs/files/meta-xt-prod-extra/recipes-extended/guest-addons/files/domd-h3ulcb-4x2g-kf.cfg
recipes-dom0/dom0-image-thin-initramfs/files/meta-xt-prod-extra/recipes-extended/guest-addons/files/domd-h3ulcb-4x2g.cfg
recipes-dom0/dom0-image-thin-initramfs/files/meta-xt-prod-extra/recipes-extended/guest-addons/files/domd-h3ulcb.cfg
recipes-dom0/dom0-image-thin-initramfs/files/meta-xt-prod-extra/recipes-extended/guest-addons/files/domd-salvator-x-h3-4x2g.cfg
recipes-dom0/dom0-image-thin-initramfs/files/meta-xt-prod-extra/recipes-extended/guest-addons/files/domd-salvator-x-h3.cfg
recipes-dom0/dom0-image-thin-initramfs/files/meta-xt-prod-extra/recipes-extended/guest-addons/files/domd-salvator-x-m3.cfg
recipes-dom0/dom0-image-thin-initramfs/files/meta-xt-prod-extra/recipes-extended/guest-addons/files/domd-salvator-xs-h3-4x2g.cfg
recipes-dom0/dom0-image-thin-initramfs/files/meta-xt-prod-extra/recipes-extended/guest-addons/files/domd-salvator-xs-h3.cfg
recipes-dom0/dom0-image-thin-initramfs/files/meta-xt-prod-extra/recipes-extended/guest-addons/files/domu-h3ulcb.cfg
recipes-dom0/dom0-image-thin-initramfs/files/meta-xt-prod-extra/recipes-extended/guest-addons/files/domu-salvator-x-h3-4x2g.cfg
recipes-dom0/dom0-image-thin-initramfs/files/meta-xt-prod-extra/recipes-extended/guest-addons/files/domu-salvator-x-h3.cfg
recipes-dom0/dom0-image-thin-initramfs/files/meta-xt-prod-extra/recipes-extended/guest-addons/files/domu-salvator-x-m3.cfg

Set the following values for all machines except m3ulcb/salvator-xs-m3n
(these two machines already have actual values):
1. For DomD:
XT page allocator size - 32MB
XT CMA allocator size - 64MB
2. For DomU/DomA:
XT page allocator size - 2MB
XT CMA allocator size - 4MB

dom0: Reduce XT page/CMA allocator size in guest domains

---

recipes-dom0/dom0-image-thin-initramfs/files/meta-xt-prod-extra/recipes-extended/guest-addons/files/doma-salvator-generic.cfg
recipes-dom0/dom0-image-thin-initramfs/files/meta-xt-prod-extra/recipes-extended/guest-addons/files/doma-salvator-x-h3-4x2g.cfg
recipes-dom0/dom0-image-thin-initramfs/files/meta-xt-prod-extra/recipes-extended/guest-addons/files/domd-h3ulcb-4x2g-kf.cfg
recipes-dom0/dom0-image-thin-initramfs/files/meta-xt-prod-extra/recipes-extended/guest-addons/files/domd-h3ulcb-4x2g.cfg
recipes-dom0/dom0-image-thin-initramfs/files/meta-xt-prod-extra/recipes-extended/guest-addons/files/domd-h3ulcb.cfg
recipes-dom0/dom0-image-thin-initramfs/files/meta-xt-prod-extra/recipes-extended/guest-addons/files/domd-salvator-x-h3-4x2g.cfg
recipes-dom0/dom0-image-thin-initramfs/files/meta-xt-prod-extra/recipes-extended/guest-addons/files/domd-salvator-x-h3.cfg
recipes-dom0/dom0-image-thin-initramfs/files/meta-xt-prod-extra/recipes-extended/guest-addons/files/domd-salvator-x-m3.cfg
recipes-dom0/dom0-image-thin-initramfs/files/meta-xt-prod-extra/recipes-extended/guest-addons/files/domd-salvator-xs-h3-4x2g.cfg
recipes-dom0/dom0-image-thin-initramfs/files/meta-xt-prod-extra/recipes-extended/guest-addons/files/domd-salvator-xs-h3.cfg

Current XT CMA allocator size (64MB) was believed to be enough
for running single DomU/DomA (where display systems use
"double-buffering" mode) with PV PVRKM and PV Display running.
But as it turned out, that value is insufficient for running Weston
applications in fullscreen mode on DomU. In this case more display memory
needs to be mapped from DomU to DomD at run-time.
This patch increases both DomD memory and xt_cma size by 32MB and
decreases DomA memory by 32MB respectively (we do not need to decrease
DomU memory as we provide only 1536MB to it).
Please note, XT CMA allocator size should be reconsidered again
if, for example, there is a need to run two DomU/DomA with display
and graphic enabled or enable "triple/quad-buffering" mode for
display systems on these domains.
Reported-by: …

dom0: Reconsider XT CMA allocator size in DomD

---

doc/mk_sdcard_image.sh

In order to speed up flashing of image to SD card it's good
to use bmaptool. This tools requires presence not only .img
but also .bmap file created for .img. This step can be done
by mk_sdcard_image.sh on PC with bmaptool installed.
Note: bmaptool writes image x3-x5 faster that 'dd' depending
on image content.

mk_sdcard_image: create .bmap file for image if possible

---

recipes-domd/domd-image-weston/files/meta-xt-prod-extra/recipes-core/base-files/base-files_%.bbappend

We see that execution of 'resize' affects some applications during
SSH connection. Also this command is used only for interactive console.
This patch is assembly of two patches from meta-xt-prod-tu2019-demo:
ff27d56 Avoid resizing of console for SSH connections
c39cb17 domd: hide '$' from bitbake
Sign-off's are taken from original patches.

domd: Avoid resizing of console for SSH connections

---

recipes-domd/domd-image-weston/files/meta-xt-prod-extra/recipes-graphics/mesa/mesa_%.bbappend
recipes-domu/domu-image-weston/files/meta-xt-prod-extra/recipes-graphics/mesa/mesa_%.bbappend

because it already has the necessary header (EGL/eglwaylandext.h)
in the pkg itself.
The following has been removed 0001-EGL-eglext.h-Include-eglmesaext.h.patch
Modified gles-module-egl-headers.inc
Signed-off-by: Usyk Ihor <ihor_usyk@epam.com>

New GFX pkg does not need header from mesa

---

conf/layer.conf
recipes-dom0/dom0-image-thin-initramfs/files/meta-xt-prod-extra/conf/layer.conf
recipes-domd/domd-image-weston/files/meta-xt-prod-extra/conf/layer.conf
recipes-domu/domu-image-android/files/meta-xt-prod-extra/conf/layer.conf
recipes-domu/domu-image-fusion/files/meta-xt-prod-extra/conf/layer.conf
recipes-domu/domu-image-weston/files/meta-xt-prod-extra/conf/layer.conf

Provide LAYERSERIES_COMPAT_ to layers
Add
LAYERSERIES_COMPAT_meta-xt-prod* = "thud"
to most of layers.
According to Yocto Mega-Manual:
"Setting LAYERSERIES_COMPAT is required by the Yocto Project
Compatible version 2 standard. The OpenEmbedded build system
produces a warning if the variable is not set for any given layer."
Also:
"If a layer sets a value that does not include the current version
("sumo" for the 2.5 release), then an error will be produced."
Pay attention that two layers were skipped as not tested againt thud:
- dom0-image-resque-initramfs
- domu-image-litmusrt

Provide LAYERSERIES_COMPAT_ to layers

---

recipes-domd/domd-image-weston/files/meta-xt-prod-extra/recipes-bsp/arm-trusted-firmware/files/0001-rcar-Use-UART-instead-of-Secure-DRAM-area-for-loggin.patch

do_patch complains about 0001-rcar-Use-UART-instead-of-Secure-DRAM-area-for-loggin.patch:
"Some of the context lines in patches were ignored. This can lead to
incorrectly applied patches."

armtf: Update patch in a recipe to avoid WARNING during do_patch

---

recipes-domd/domd-image-weston/files/meta-xt-prod-extra/doc/local.conf.rcar-domd-image-weston

We add 'rcar' to MACHINEOVERRIDES for every machine described in
meta-xt-images/machine/meta-xt-images-rcar-gen3/conf/machine
So there is no need to duplicate 'rcar' as far as this results in
additional search path during fetch step.

domd: Remove redundant 'rcar' from MACHINEOVERRIDES

---

recipes-domd/domd-image-weston/files/meta-xt-prod-extra/recipes-graphics/rcar-proprietary-graphic/rcar-proprietary-graphic.bb
recipes-domu/domu-image-weston/files/meta-xt-prod-extra/recipes-graphics/rcar-proprietary-graphic/rcar-proprietary-graphic.bb

Check presense of XT_RCAR_EVAPROPRIETARY_DIR before
set SRC_URI to proprietary graphics binary.

Wrap usage of proprietary graphics binaries

---

recipes-dom0/dom0-image-thin-initramfs/files/meta-xt-prod-extra/recipes-extended/guest-addons/files/doma-salvator-generic.cfg
recipes-dom0/dom0-image-thin-initramfs/files/meta-xt-prod-extra/recipes-extended/guest-addons/files/doma-salvator-x-h3-4x2g.cfg

printk.devkmsg=on was added for debugging purposes and
needed for init specific use-cases.

doma: Decrease init logs verbosity

---

recipes-dom0/dom0-image-thin-initramfs/files/meta-xt-prod-extra/doc/local.conf.dom0-image-minimal-initramfs
recipes-domd/domd-image-weston/files/meta-xt-prod-extra/doc/local.conf.rcar-domd-image-weston

As per default settings in guest domain and media pipeline
configuration files the "HDMI_IN Camera" will be used.

[Do not merge until agreed] Enable PV Camera support

---

recipes-domu/domu-image-android/files/meta-xt-prod-extra/doc/bblayers.conf.domu-image-android
recipes-domu/domu-image-android/files/meta-xt-prod-extra/doc/local.conf.domu-image-android

doma: Remove Java support for Android
Android uses internal tools for the build. There is
no need to provide external JVM/JDK for the build.

Remove Java build support for Android

---

INSTALL.txt

PyGitHub is used by build-scripts/build_prod.py

INSTALL.txt: add pygithub to list of required packages

---

recipes-domd/domd-image-weston/domd-image-weston.bbappend
recipes-domu/domu-image-weston/domu-image-weston.bbappend

Usage of default value for XT_PRODUCT_NAME has few negative results:
- possible usage of manifest from incorrect folder and hard to find errors
- misleading info during read of recipe especially for forked products
Taking into account above mentioned it's better to get build error
on early stage than correct build with incorrect manifest.

domd: domu: Remove default value of XT_PRODUCT_NAME

---

recipes-dom0/dom0-image-rescue-initramfs/files/meta-xt-prod-extra/doc/bblayers.conf.dom0-image-rescue-initramfs
recipes-dom0/dom0-image-thin-initramfs/files/meta-xt-prod-extra/doc/bblayers.conf.dom0-image-minimal-initramfs
recipes-domd/domd-image-weston/files/meta-xt-prod-extra/doc/bblayers.conf.rcar-domd-image-weston
recipes-domu/domu-image-android/files/meta-xt-prod-extra/doc/bblayers.conf.domu-image-android
recipes-domu/domu-image-fusion/files/meta-xt-prod-extra/doc/bblayers.conf.domf-image-minimal
recipes-domu/domu-image-weston/files/meta-xt-prod-extra/doc/bblayers.conf.rcar-domu-image-weston

BBLAYERS_NON_REMOVABLE was used only by Hob.
This variable was removed from yocto in March 2016 and
there is no reason for us to keep it.

Remove BBLAYERS_NON_REMOVABLE

---

recipes-dom0/dom0-image-thin-initramfs/files/meta-xt-prod-extra/recipes-extended/guest-addons/files/doma-vdevices.cfg

According to Android's CDD we need to support following sample rates
for playback and record:
8000, 11025, 16000, 22050, 32000, 44100, 48000
Remove 24000 as not supported.

doma: audio: Declare support for required sample rates

---

recipes-domu/domu-image-android/files/meta-xt-prod-extra/recipes-extended/android/android.bbappend

The commit to support p2m lookup has been reverted from master. As result-
some machines are not supported anymore (in main branch). It has been decided
to create a separate branch for prod-devel to leave the possibility to handle
the old behavior. The master of android_manifest contains the reference at 'cleaned'
pvr_km_vgpu_img, this is because the branch android-10.0.0_r3-master-unsafe has been created
to have the reference at 'not cleaned' pvr_km_vgpu_img.
> Not correct patch description, since it is not cleaned branch
Here is an explanation  -why the branch has been created. The description has the information that this branch supports 'not cleaned' pvr_km_vgpu_img: "his is because the branch android-10.0.0_r3-master-unsafe has been …

Switch android_manifest branch at android-10.0.0_r3-master-unsafe

---

inc/xen-version.inc
recipes-dom0/dom0-image-thin-initramfs/dom0-image-thin-initramfs.bbappend
recipes-domd/domd-image-weston/files/meta-xt-prod-extra/recipes-kernel/kernel-module-gles/kernel-module-gles_1.11.bbappend
recipes-domu/domu-image-weston/files/meta-xt-prod-extra/recipes-kernel/kernel-module-gles/kernel-module-gles_1.11.bbappend

The branch of xen is reconfigured at RELEASE-4.13.0-xt0.2.prod-devel
The feature process_p2m_lookup has been reverted from the RELEASE-4.13.0-xt0.2.prod-devel
Some machines do not work now, there are
salvator-x-m3, salvator-xs-h3, h3ulcb, m3ulcb, salvator-x-h3
In a case, if local.conf has one of the mentioned machines as current one,
the warning and valid branch of xen(RELEASE-4.13.0-xt0.1.prod-devel) are displayed
The recipe kernel-module-gles_1.11.bbappend has been modified for
domd and domu(weston) to fix the version of pvr_km_vgpu_img at "1.11/5516664-1"
Use prod-devel branch prod-devel-unsafe to support the old behavior.

Removing support of process_p2m_lookup

---

inc/xen-version.inc
recipes-dom0/dom0-image-thin-initramfs/dom0-image-thin-initramfs.bbappend
recipes-dom0/dom0-image-thin-initramfs/files/meta-xt-prod-extra/recipes-core/images/core-image-thin-initramfs.bbappend
recipes-dom0/dom0-image-thin-initramfs/files/meta-xt-prod-extra/recipes-extended/xen/files/0001-libxl-Add-DTB-compatible-list-to-config-file.patch
recipes-dom0/dom0-image-thin-initramfs/files/meta-xt-prod-extra/recipes-extended/xen/files/0002-libxl-Add-DTB-passthrough-nodes-list.patch
recipes-domd/domd-image-weston/domd-image-weston.bbappend
recipes-domd/domd-image-weston/files/meta-xt-prod-extra/recipes-extended/xen/xen_git.bbappend

The one important thing here is that now EXPERT mode can be selected
from the menuconfig directly.
There is no need to use XEN_CONFIG_EXPERT=y on the make command line
anymore.
Also install xenhypfs tool.

Switch to Xen v4.14 release

---

recipes-domd/domd-image-weston/files/meta-xt-prod-extra/recipes-graphics/rcar-proprietary-graphic/rcar-proprietary-graphic.bb
recipes-domu/domu-image-weston/files/meta-xt-prod-extra/recipes-graphics/rcar-proprietary-graphic/rcar-proprietary-graphic.bb

This reverts commit 48607110cdf3f4aabb52d4d78ad403588be975e7.
Variable XT_RCAR_EVAPROPRIETARY_DIR, used in reverted patch,
is not available indomain's local.conf.
Also patch was not tested deep enough despite comments in PR.

Revert "Wrap usage of proprietary graphics binaries in domd/domu"

---

recipes-dom0/dom0-image-thin-initramfs/files/meta-xt-prod-extra/recipes-bsp/u-boot/u-boot_%.bbappend
recipes-dom0/dom0-image-thin-initramfs/files/meta-xt-prod-extra/recipes-core/images/core-image-thin-initramfs.bbappend
recipes-dom0/dom0-image-thin-initramfs/files/meta-xt-prod-extra/recipes-extended/guest-addons/files/doma-generic-h3-4x2g.cfg
recipes-dom0/dom0-image-thin-initramfs/files/meta-xt-prod-extra/recipes-extended/guest-addons/files/doma-generic-h3.cfg

1.Remove a "coping" of the DomA Linux kernel into DOM0 initramfs
The following files were modified to change the kernel publishing at u-boot.bin
-doma-generic-h3-4x2g.cfg
-doma-generic-h3.cfg
2.Build a u-boot during the Dom0 build from https://github.com/xen-troops/u-boot (as for the proof of concept this branch: https://github.com/arminn/u-boot/commits/mr_rcar_pvblock should be used).
-The new recipe u-boot_%.bbappend has been added with the corresponded SRC_URI
-core-image-thin-initramfs.bbappend has been modified to build the u-boot.
3.Copy u-boot.bin into DOM0 initramfs
core-image-thin-initramfs.bbappend has been modified to add the u-boot into image installation

Place u-boot in to Initramfs

---

INSTALL.txt

The following packages must be pre-installed
pyelftools
pycryptodomex
gcc-aarch64-linux-gnu

INSTALL.txt: Add the packages to support android build

---

recipes-domd/domd-image-weston/files/meta-xt-prod-extra/recipes-graphics/wayland/weston/kingfisher/vsp2.rules

Existing vsp2.rules that identifies fe960000.vsp as a H/W for
VSP renderer is suitable for Salvator-X board, but on Kingfisher
it leads to blank screen. On Kingfisher we need to use another H/W
which is fe920000.vsp.
Place new file into a folder dedicated for Kingfisher.

Add vsp2.rules for Kingfisher

---

recipes-domd/domd-image-weston/files/meta-xt-prod-extra/recipes-kernel/linux/linux-renesas/0001-HACK-Allow-pci-back-run-in-DomD.patch
recipes-domd/domd-image-weston/files/meta-xt-prod-extra/recipes-kernel/linux/linux-renesas_%.bbappend

pci-back has a check if it runs in the initial domain, e.g. Domain-0,
which is not the case when it runs in the driver domain DomD.

domd: Allow pci-back to run in DomD

---

recipes-domd/domd-image-weston/files/meta-xt-prod-extra/recipes-kernel/linux/linux-renesas/0001-HACK-Make-rcar-gen3-PCI-work-through-ECAM.patch

This is due to ARM's changes in vPCI addresses used.

domd: Update emulated ECAM bridge addresses

---

recipes-dom0/dom0-image-thin-initramfs/files/meta-xt-prod-extra/recipes-extended/guest-addons/files/domd-salvator-x-h3-4x2g.cfg
recipes-dom0/dom0-image-thin-initramfs/files/meta-xt-prod-extra/recipes-extended/guest-addons/files/domu-generic-h3-4x2g.cfg
recipes-domd/domd-image-weston/files/meta-xt-prod-extra/recipes-kernel/linux/linux-renesas/r8a7795-salvator-x-4x2g-dom0.dts

Taking into the account that on Gen3 the IPMMU can't distinguish between
different PCI Functions we propose the following settings:
&pciec0 {
iommu-map = <0x0 &ipmmu_hc 0x0 0x1>;
iommu-map-mask = <0x0>;
};
which means that all Requester IDs will be mapped to the uTLB 0
of ipmmu_hc.
According to:
https://www.kernel.org/doc/Documentation/devicetree/bindings/pci/pci-iommu.txt

Describe PCI device(s)-IOMMU(s) connection using DT PCI-IOMMU bindings

---

recipes-dom0/dom0-image-thin-initramfs/files/meta-xt-prod-extra/recipes-core/images/core-image-thin-initramfs.bbappend
recipes-dom0/dom0-image-thin-initramfs/files/meta-xt-prod-extra/recipes-kernel/linux/linux-generic-armv8.bbappend
recipes-dom0/dom0-image-thin-initramfs/files/meta-xt-prod-extra/recipes-kernel/linux/linux-generic-armv8/qemu-xen/8139cp.cfg

Build Linux kernel module for:
Ethernet controller: Realtek Semiconductor Co., Ltd. RTL-8100/8101L/8139 PCI Fast Ethernet Adapter (rev 20)
instead of having it built-in.

qemu/dom0: Build Realtek 8139cp as a kernel module

---

recipes-domd/domd-image-weston/files/meta-xt-prod-extra/recipes-extended/xen/xen_git.bbappend

After switching to a newer Xen branch we need to update xenpolicy file
name.

domd: Update xenpolicy file name

---

INSTALL.txt

List of supported machines is formatted in order to
make it easier to read and easier to identify which machine
has limited support.

INSTALL.txt: Reformat list of supported machines

---

recipes-domd/domd-image-weston/domd-image-weston.bbappend

Patch for meta-rcar-gen3-adas is only applicable for h3ulcb-4x2g-kf.
Assign patch to coresponding SRC_URI.
Signed-off-by: Valerii Chubar <valerii_chubar@epam.com>

domd: meta-renesas: Apply rcar-gen3-adas patch only for h3ulcb-4x2g-kf

---

recipes-domu/domu-image-weston/files/meta-xt-prod-extra/recipes-graphics/images/core-image-weston.bbappend

Disable psplash from installation, because it not functional.
It requires a frame buffer which is not available in DomU.
Signed-off-by: Valerii Chubar <valerii_chubar@epam.com>

domu: remove psplash

---

recipes-domd/domd-image-weston/files/meta-xt-prod-extra/recipes-core/base-files/base-files_%.bbappend
recipes-domd/domd-image-weston/files/meta-xt-prod-extra/recipes-core/netbase/netbase_%.bbappend

Move visservice host to base-files to prevent build
time race conditions between base-files and netbase.

visservice: Move visservice host to base-files

---

recipes-domd/domd-image-weston/domd-image-weston.bbappend
recipes-domd/domd-image-weston/files/meta-xt-prod-extra/recipes-support/netevent/netevent_%.bbappend

Sometimes we observe race during multithreaded compilation
so it's better to build netevent in one thread.

domd: Compile netevent in one thread

---

recipes-domd/domd-image-weston/domd-image-weston.bbappend

This patch adds condition for masking of netevent recipe
for all boards except kingfisher.
Fixes: 032cc65208c1d65ecb895745eaa66bf070aba350

domd: Fix BBMASK for netevent for not Kingfisher

---

recipes-domd/domd-image-weston/files/meta-xt-prod-extra/recipes-kernel/linux/linux-renesas/r8a7795-h3ulcb-4x2g-kf-dom0.dts

Fix for:
xl create -c /xt/dom.cfg/domd.cfg
...
(XEN) XEN_DOMCTL_assign_dt_device: assign "/soc/dma-controller@ffc10000" to dom2 failed (-22)
libxl: error: libxl_create.c:1789:libxl__add_dtdevs: Domain 2:xc_assign_dtdevice failed: -1
libxl: error: libxl_create.c:1855:domcreate_attach_devices: Domain 2:unable to add none devices
(XEN) Removed GSX d2 (OSID 0)

h3ulcb-4x2g-kf: Enable missing ipmmu_rt in dom0 device-tree

---

recipes-domd/domd-image-weston/files/meta-xt-prod-extra/recipes-aos/aos-vis/files/aos_vis.cfg

According to
https://www.w3.org/TR/vehicle-information-service/#initialisation-of-the-websocket
default port should be 443.

domd: Fix port used by VIS server to 443

---

recipes-domd/domd-image-weston/files/meta-xt-prod-extra/recipes-extended/guest-addons/files/xenbr0-systemd-networkd.conf
recipes-domd/domd-image-weston/files/meta-xt-prod-extra/recipes-extended/guest-addons/guest-addons.bb

xenbr0-systemd-networkd.conf was needed as a workaround for
the issue with checksum for TX packets. The issue doesn't
exist anymore therefore file is not needed.

domd: remove xenbr0-systemd-networkd.conf as outdated

---

recipes-dom0/dom0-image-thin-initramfs/files/meta-xt-prod-extra/recipes-extended/guest-addons/files/doma-generic-h3-4x2g.cfg
recipes-dom0/dom0-image-thin-initramfs/files/meta-xt-prod-extra/recipes-extended/guest-addons/files/doma-generic-h3.cfg
recipes-dom0/dom0-image-thin-initramfs/files/meta-xt-prod-extra/recipes-extended/guest-addons/files/doma-generic-m3-2x4g.cfg

Assignment of IP is performed by user space, therefore we have
no need to send DHCP requests during the start of the kernel.
Suggested-by: Volodymyr Babchuk <volodymyr_babchuk@epam.com>

doma.cfg: Remove `ip=dhcp` from kernel command-line

---

recipes-domd/domd-image-weston/files/meta-xt-prod-extra/recipes-connectivity/dnsmasq/dnsmasq_2.%.bbappend
recipes-domd/domd-image-weston/files/meta-xt-prod-extra/recipes-extended/guest-addons/files/port-forward-systemd-networkd.conf
recipes-domd/domd-image-weston/files/meta-xt-prod-extra/recipes-extended/guest-addons/guest-addons.bb

This change removes not related records made to `dnsmasq.conf`
and `port-forward-systemd-networkd.conf`.

domd: net: Make network settings according to guest installed

---

recipes-dom0/dom0-image-rescue-initramfs/files/meta-xt-prod-extra/recipes-kernel/linux/linux-generic-armv8.bbappend
recipes-dom0/dom0-image-thin-initramfs/files/meta-xt-prod-extra/recipes-kernel/linux/linux-generic-armv8.bbappend
recipes-domd/domd-image-weston/files/meta-xt-prod-extra/recipes-core/dbus/dbus-cxx_0.10.0.bbappend
recipes-domd/domd-image-weston/files/meta-xt-prod-extra/recipes-extended/xt-log/xt-log_git.bbappend
recipes-domd/domd-image-weston/files/meta-xt-prod-extra/recipes-graphics/wayland/wayland-ivi-extension_2.2.0_weston-8.bb
recipes-domd/domd-image-weston/files/meta-xt-prod-extra/recipes-kernel/linux-libc-headers/linux-libc-headers_%.bbappend
recipes-domd/domd-image-weston/files/meta-xt-prod-extra/recipes-kernel/linux/linux-renesas_%.bbappend
recipes-domu/domu-image-fusion/files/meta-xt-prod-extra/recipes-kernel/linux/linux-generic-armv8.bbappend
recipes-domu/domu-image-weston/files/meta-xt-prod-extra/recipes-kernel/linux-libc-headers/linux-libc-headers_%.bbappend
recipes-domu/domu-image-weston/files/meta-xt-prod-extra/recipes-kernel/linux/linux-renesas_%.bbappend

URIs: replace git protocol with https one for the github sources.
Use https instead of git because unauthenticated git protocol is disabled by github.

URIs: replace git protocol with https one for the github sources.

---

recipes-dom0/dom0-image-rescue-initramfs/files/meta-xt-prod-extra/recipes-kernel/linux/linux-generic-armv8.bbappend
recipes-dom0/dom0-image-thin-initramfs/files/meta-xt-prod-extra/recipes-kernel/linux/linux-generic-armv8.bbappend
recipes-domd/domd-image-weston/files/meta-xt-prod-extra/recipes-core/dbus/dbus-cxx_0.10.0.bbappend
recipes-domd/domd-image-weston/files/meta-xt-prod-extra/recipes-extended/xt-log/xt-log_git.bbappend
recipes-domd/domd-image-weston/files/meta-xt-prod-extra/recipes-graphics/wayland/wayland-ivi-extension_2.2.0_weston-8.bb
recipes-domd/domd-image-weston/files/meta-xt-prod-extra/recipes-kernel/linux-libc-headers/linux-libc-headers_%.bbappend
recipes-domd/domd-image-weston/files/meta-xt-prod-extra/recipes-kernel/linux/linux-renesas_%.bbappend
recipes-domu/domu-image-fusion/files/meta-xt-prod-extra/recipes-kernel/linux/linux-generic-armv8.bbappend
recipes-domu/domu-image-weston/files/meta-xt-prod-extra/recipes-kernel/linux-libc-headers/linux-libc-headers_%.bbappend
recipes-domu/domu-image-weston/files/meta-xt-prod-extra/recipes-kernel/linux/linux-renesas_%.bbappend

URIs: replace git protocol with https one for the github sources.
Use https instead of git because unauthenticated git protocol is disabled by github.

URIs: replace git protocol by https one for the github sources. 

---

recipes-domd/domd-image-weston/domd-image-weston.bbappend
recipes-domd/domd-image-weston/files/meta-xt-prod-extra/recipes-core/base-files/base-files_%.bbappend
recipes-domd/domd-image-weston/files/meta-xt-prod-extra/recipes-graphics/images/core-image-weston.bbappend

This patch introduces new variable XT_USE_VIS_SERVER.
When this variable is not defined or empty then VIS
components will be not used in build of DomD.
If XT_USE_VIS_SERVER is not empty then VIS components
will be used in build as sources or prebuilt binary,
depending on two other mutually exclusive variables,
already present in sources:
- AOS_VIS_PLUGINS for build from sources;
- AOS_VIS_PACKAGE_DIR for prebuilt binary.
We need to take into account that VIS related manipulations
are performed on two levels: upper and lower (DomD).
On upper level we use variable XT_USE_VIS_SERVER as is.
On lower level (inside build of DomD) we use
DISTRO_FEATURE "vis" as "more natural for Linux"
presentation of XT_USE_VIS_SERVER switch. …

domd: Wrap VIS related code by XT_USE_VIS_SERVER
